version: '2'
services:
    nginx:
        image: nginx:1.11.5-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        volumes_from:
            - application_source
        links:
            - php

    php:
        build: ./docker/php
        ports:
            - 9000:9000
        volumes_from:
            - application_source
        links:
            - mysql

    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        user: "1000:50"
        volumes:
            - ./data/mysql/:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    application_source:
        image: tianon/true:latest
        volumes:
            - ./project/:/var/www/html
